### ISSUE TITLE
CSS and SCSS properties A-Z sorting

### ISSUE THREAD

**Issue by yetiasg** [Selleo/stylelint-config-selleo#6]
## Short overview
The package should warn if properties are not sorted alphabetically. It should be possible to automatically sort properties using some script

## Short overview
Find the best way to handle A-Z properties sorting 

## ToDo
- [x] Find sylelint plugin responsible for sorting
- [x] Add sorting rules -> alphabetically sorted list of properties 
- [x] Add stylelint script that sorts properties
