### ISSUE TITLE
Update readme - how to start with the package

### ISSUE THREAD

**Issue by yetiasg** [Selleo/stylelint-config-selleo#7]
## Short overview
Describe all steps how to start using this package 

## ToDo
Either use a more detailed description or provide a list with checkboxes.
- [x] VSCode Info how to enable autofix on file save
- [x] WebStorm Info how to enable autofix on file save
- [x] Script for auto sorting and linting style properties 
- [x] Prettierignore info
